// Code generated by MockGen. DO NOT EDIT.
// Source: suggestions.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "car-comparison-service/db/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIVehicleSuggestions is a mock of IVehicleSuggestions interface.
type MockIVehicleSuggestions struct {
	ctrl     *gomock.Controller
	recorder *MockIVehicleSuggestionsMockRecorder
}

// MockIVehicleSuggestionsMockRecorder is the mock recorder for MockIVehicleSuggestions.
type MockIVehicleSuggestionsMockRecorder struct {
	mock *MockIVehicleSuggestions
}

// NewMockIVehicleSuggestions creates a new mock instance.
func NewMockIVehicleSuggestions(ctrl *gomock.Controller) *MockIVehicleSuggestions {
	mock := &MockIVehicleSuggestions{ctrl: ctrl}
	mock.recorder = &MockIVehicleSuggestionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIVehicleSuggestions) EXPECT() *MockIVehicleSuggestionsMockRecorder {
	return m.recorder
}

// CreateKey mocks base method.
func (m *MockIVehicleSuggestions) CreateKey(ctx context.Context, vehicleId string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKey", ctx, vehicleId)
	ret0, _ := ret[0].(string)
	return ret0
}

// CreateKey indicates an expected call of CreateKey.
func (mr *MockIVehicleSuggestionsMockRecorder) CreateKey(ctx, vehicleId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKey", reflect.TypeOf((*MockIVehicleSuggestions)(nil).CreateKey), ctx, vehicleId)
}

// GetVehicleSuggestionsDetails mocks base method.
func (m *MockIVehicleSuggestions) GetVehicleSuggestionsDetails(ctx context.Context, key string) ([]model.VehicleSuggestionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVehicleSuggestionsDetails", ctx, key)
	ret0, _ := ret[0].([]model.VehicleSuggestionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVehicleSuggestionsDetails indicates an expected call of GetVehicleSuggestionsDetails.
func (mr *MockIVehicleSuggestionsMockRecorder) GetVehicleSuggestionsDetails(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVehicleSuggestionsDetails", reflect.TypeOf((*MockIVehicleSuggestions)(nil).GetVehicleSuggestionsDetails), ctx, key)
}

// SetVehicleSuggestionsDetails mocks base method.
func (m *MockIVehicleSuggestions) SetVehicleSuggestionsDetails(ctx context.Context, key string, res []model.VehicleSuggestionResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetVehicleSuggestionsDetails", ctx, key, res)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetVehicleSuggestionsDetails indicates an expected call of SetVehicleSuggestionsDetails.
func (mr *MockIVehicleSuggestionsMockRecorder) SetVehicleSuggestionsDetails(ctx, key, res interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVehicleSuggestionsDetails", reflect.TypeOf((*MockIVehicleSuggestions)(nil).SetVehicleSuggestionsDetails), ctx, key, res)
}
